# services missing: nodejs, nginx
version: '3.9'
services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - MYSQL_DATABASE=baseapi
      - MYSQL_ROOT_PASSWORD=Amela@123a@
  redis:
    image: 'redis:6.0.10'
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=mysql
    links: 
      - redis
      - mysql
    
  
